name: Extract Secrets Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  extract-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use a Secret in a Command
        run: |
          echo "Using the secret in a command:"
          echo "${{ env.SOMETHING }}" # This will be redacted in logs
        env:
          SOMETHING: ${{ secrets.MY_SECRET }}

      - name: Print Secret
        run: |
          echo $SOMETHING >> .env
          cat .env
        shell: bash
        env:
          SOMETHING: ${{ secrets.MY_SECRET }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: something
          include-hidden-files: true
          path: .env
